"""empty message

Revision ID: 010e2a6cb0e9
Revises: 05f2dd943c99
Create Date: 2019-02-22 10:28:13.580773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010e2a6cb0e9'
down_revision = '05f2dd943c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.Column('slug', sa.String(length=190), nullable=False),
    sa.Column('function', sa.String(length=190), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=190), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_uid'), 'persons', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_uid'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
