"""empty message

Revision ID: 2dfc6627f327
Revises: 
Create Date: 2019-02-27 10:39:38.193925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dfc6627f327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'location',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=130),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=130),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('users', 'location',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
