"""empty message

Revision ID: 4d24f3b51cc8
Revises: 010e2a6cb0e9
Create Date: 2019-02-22 11:23:42.131099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d24f3b51cc8'
down_revision = '010e2a6cb0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('slug', sa.String(length=190), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'slug')
    # ### end Alembic commands ###
