"""empty message

Revision ID: d165f1b03305
Revises: 6208655c9dd3
Create Date: 2019-02-20 19:45:06.926611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd165f1b03305'
down_revision = '6208655c9dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'category_id')
    # ### end Alembic commands ###
