"""empty message

Revision ID: e9e37630867b
Revises: 4d24f3b51cc8
Create Date: 2019-02-22 19:21:03.929598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e37630867b'
down_revision = '4d24f3b51cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('vue', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('vue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'vue')
    op.drop_column('articles', 'vue')
    # ### end Alembic commands ###
